# User config
author: "Karndeep Dhami"
tagline: "Portfolio"
description: "I am a Computer Scientist who Researches, Designs, Develops, and Codes"
keywords: "Computer Science, Human Computer Interaction"
email: "karndhami@gmail.com"
linkedin: "https://www.linkedin.com/in/karndeepdhami"
github: "https://github.com/ksdhami"

# Site config
# baseurl: "/pineapple"
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed